-- AlterTable
ALTER TABLE "seller_applications" ADD COLUMN     "agreedToCommissionTerms" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "approxExportOrders" TEXT,
ADD COLUMN     "businessType" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "companyIncorporation" TEXT,
ADD COLUMN     "country" TEXT DEFAULT 'India',
ADD COLUMN     "craftCategories" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "exportCountries" TEXT,
ADD COLUMN     "giTaggedProducts" TEXT,
ADD COLUMN     "gstRegistration" TEXT,
ADD COLUMN     "hearAboutUs" TEXT,
ADD COLUMN     "iecStatus" TEXT,
ADD COLUMN     "instagramFollowers" INTEGER,
ADD COLUMN     "instagramHandle" TEXT,
ADD COLUMN     "monthlySalesVolume" TEXT,
ADD COLUMN     "otherPlatforms" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "productDescription" TEXT,
ADD COLUMN     "sellingOnAmazon" TEXT,
ADD COLUMN     "shippedInternationally" BOOLEAN,
ADD COLUMN     "websiteOrSocialLink" TEXT;
