'use client'

import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { Pause, Play } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useAuthStore } from '@/lib/store/useAuthStore'

// ─── Media ────────────────────────────────────────────────────────────────────
// Illustrative scene only — not inventory. The poster is the video's own first
// frame, generated by Cloudinary from the same asset (no new imagery).

const HERO_VIDEO_SRC =
  'https://res.cloudinary.com/dxnqyvcdl/video/upload/q_auto,f_auto/v1789016854/Handwoven_Textile____Threads_o_k286tz.mp4'
const HERO_POSTER_SRC =
  'https://res.cloudinary.com/dxnqyvcdl/video/upload/so_0,q_auto/v1789016854/Handwoven_Textile____Threads_o_k286tz.jpg'

/** Spec fallback while real imagery is missing / still loading. */
const HERO_FALLBACK_GRADIENT = 'linear-gradient(#0F241D, #183D33, #465C36)'

// ─── Component ────────────────────────────────────────────────────────────────

export function HeroSection() {
  const openAuthModal = useAuthStore((s) => s.openAuthModal)
  const videoRef = useRef<HTMLVideoElement>(null)
  const [isPlaying, setIsPlaying] = useState(false)

  // Autoplay only when the visitor hasn't asked for reduced motion; otherwise the
  // poster frame stays as a still image and the play control lets them opt in.
  useEffect(() => {
    const video = videoRef.current
    if (!video) return
    const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches
    if (reduced) return
    video.play().then(
      () => setIsPlaying(true),
      () => setIsPlaying(false)
    )
  }, [])

  function togglePlayback() {
    const video = videoRef.current
    if (!video) return
    if (video.paused) {
      video.play().then(
        () => setIsPlaying(true),
        () => setIsPlaying(false)
      )
    } else {
      video.pause()
      setIsPlaying(false)
    }
  }

  return (
    <section
      className="on-forest relative overflow-hidden min-h-[600px] lg:min-h-[560px] flex items-center"
      style={{ background: HERO_FALLBACK_GRADIENT }}
      aria-labelledby="home-hero-heading"
    >
      <video
        ref={videoRef}
        src={HERO_VIDEO_SRC}
        poster={HERO_POSTER_SRC}
        muted
        loop
        playsInline
        preload="metadata"
        aria-hidden="true"
        tabIndex={-1}
        className="absolute inset-0 w-full h-full object-cover object-right"
      />

      {/* Forest overlay for legibility: uniform on mobile (copy spans the full
          width), a left-to-right fade on desktop so the scene stays visible right. */}
      <div className="absolute inset-0 pointer-events-none bg-forest/75 lg:hidden" aria-hidden="true" />
      <div
        className="absolute inset-0 pointer-events-none hidden lg:block"
        style={{
          background:
            'linear-gradient(to right, rgba(24,61,51,0.94) 0%, rgba(24,61,51,0.82) 40%, rgba(24,61,51,0.25) 70%, rgba(24,61,51,0) 100%)',
        }}
        aria-hidden="true"
      />

      <div className="relative z-10 w-full sb-container py-12 lg:py-[72px]">
        <h1 id="home-hero-heading" className="type-hero text-white max-w-[700px]">
          Discover and source bestseller products for <span className="text-brass">your store</span>
        </h1>

        <p className="type-hero-body text-light-text mt-6 max-w-[560px]">
          Sign up to unlock wholesale pricing.
        </p>

        <div className="mt-8 flex flex-col sm:flex-row gap-3">
          <Button
            type="button"
            variant="onForest"
            size="lg"
            className="w-full sm:w-auto"
            onClick={() => openAuthModal('signup')}
          >
            Sign up to buy
          </Button>
          <Button asChild variant="outlineOnForest" size="lg" className="w-full sm:w-auto">
            <Link href="/collections">Browse products</Link>
          </Button>
        </div>
      </div>

      <button
        type="button"
        onClick={togglePlayback}
        aria-label={isPlaying ? 'Pause background video' : 'Play background video'}
        className="absolute z-10 bottom-4 right-4 w-11 h-11 rounded-full border border-white/70 bg-forest/60 text-white flex items-center justify-center transition-colors duration-150 hover:bg-forest"
      >
        {isPlaying ? <Pause size={16} aria-hidden="true" /> : <Play size={16} aria-hidden="true" />}
      </button>
    </section>
  )
}
