import { Router } from 'express';
import { cataloguesController } from './catalogues.controller';
import { createCatalogueSchema, idParamSchema } from './catalogues.validation';
import { paginationQuerySchema } from '../../utils/pagination';
import { validate } from '../../middleware/validate';
import { requireAgent, requireAuth } from '../../middleware/auth';
import { asyncHandler } from '../../utils/asyncHandler';

export const cataloguesRouter = Router();

/**
 * @openapi
 * /agent/catalogues:
 *   post:
 *     summary: Generate a shareable PDF catalogue from selected products (AGENT only)
 *     tags: [Catalogues]
 *     requestBody: { required: true }
 *     responses:
 *       201: { description: Catalogue generated }
 */
cataloguesRouter.post(
  '/',
  requireAuth,
  requireAgent,
  validate(createCatalogueSchema),
  asyncHandler(cataloguesController.generate),
);

/**
 * @openapi
 * /agent/catalogues:
 *   get:
 *     summary: List catalogues generated by the authenticated agent (AGENT only)
 *     tags: [Catalogues]
 *     responses:
 *       200: { description: Catalogues list }
 */
cataloguesRouter.get(
  '/',
  requireAuth,
  requireAgent,
  validate(paginationQuerySchema, 'query'),
  asyncHandler(cataloguesController.list),
);

/**
 * @openapi
 * /agent/catalogues/{id}:
 *   get:
 *     summary: Get a single catalogue for re-download (AGENT only)
 *     tags: [Catalogues]
 *     responses:
 *       200: { description: Catalogue detail }
 */
cataloguesRouter.get(
  '/:id',
  requireAuth,
  requireAgent,
  validate(idParamSchema, 'params'),
  asyncHandler(cataloguesController.getById),
);
